/** @file intercontroller.h
 *  @brief Interrupt controller emulator signal definitions.
 *
 *  This header defines the signaling constants used by the InterController Sim 
 *  process. The emulator is responsible for generating periodic time-slice 
 *  interrupts (clock) and signaling the completion of inter-process communication 
 *  (IPC) read and write operations on the pipes.
 */

#ifndef INTERCONTROLLER_H
#define INTERCONTROLLER_H

/**
 * @brief Time-slice frequency for the scheduler.
 *
 * Defines the time interval (in milliseconds) for the periodic generation 
 * of the IRQ0 interrupt, which dictates the round-robin time-slice.
 */
#define TIME_SLICE 500

/**
 * @brief System interrupt signal enumerations.
 *
 * Represents the specific interrupt request (IRQ) signals generated by the 
 * InterController Sim to notify the KernelSim of system events.
 */
typedef enum
{
    /** 
     * @brief Time-slice interrupt. 
     * Generated periodically every 500 ms to trigger a context switch.
     */
    INTERCONTROLLER_SIG_IRQ0,

    /** 
     * @brief Pipe read completion interrupt. 
     * Indicates the completion of a recv() operation on any of the active pipes.
     */
    INTERCONTROLLER_SIG_IRQ1,

    /** 
     * @brief Pipe write completion interrupt. 
     * Indicates the completion of a send() operation on any of the active pipes.
     */
    INTERCONTROLLER_SIG_IRQ2,

    /** 
     * @brief Error signal.
     * Used to indicate an internal emulator error or an invalid signal state. 
     */
    INTERCONTROLLER_SIG_ERROR
} IntercontrollerSig;

#endif /* INTERCONTROLLER_H */
